version: '3.8'
services:
  account-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: account-api
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/accountsDB
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"